# Generated by Django 4.2.15 on 2024-08-20 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_cinema_countries1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cinema',
        ),
    ]
